version: '3.8'

services:
  shared-timer-app:
    container_name: Custom_Webex_Shared_Timer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - NAME=SharedTimerApp
      - PUBLIC_URL=
      - FLASK_ENV=production
      - LOGGER_LEVEL=DEBUG
    volumes:
      - .:/app  # mounting the entire project directory
    networks:
      - shared-timer-network

networks:
  shared-timer-network:
    driver: bridge