version: '3.8'

services:
  shared-timer-app:
    container_name: FedRAMP_Webex_Shared_Timer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - NAME=SharedTimerApp
    volumes:
      - .:/app  # mounting the entire project directory
    networks:
      - shared-timer-network

networks:
  shared-timer-network:
    driver: bridge
